### PR TITLE
Fixed bot base configuration to work out-of-the-box

### PR DESCRIPTION
**Pull request by ThoDon**
- Had to bump vinted-api version to get the correct api URL for the bot.
- Had to use another form of timestamp to make everything work, since "created_at_ts" was removed from objects returned from vinted api.
- Since some more informations were removed, I made some cleaning in the code as I would have done for me.

Now missing datas  from Vinted API :

1.  item.status => x
2. item.size => used size_title instead
3. item.created_at_ts => based every timestamp calculations on the item.photo.high_resolution.timestamp, which might not be as accurate as the previous ts, but do work well on my side for now.
4. vendor infos => x

### CODE REVIEW

**Comment by kevinfosse** [comment]
> You do get one item when you subscribe to researches, which indicate that the fix for vinted-api version is working, but as for the new item appearing in the bot, it might takes some times (around 5 minutes, sometimes more) to receive the notification.
> 
> Sadly, it depends entirely on the Vinted side, depends on how much times they takes to reflect the new items on their API publicly

My question may seem silly, but wouldn't it be easier to compare nicknames or prices? 
I have the impression that the bot can't display all the matches

I don't know if the API naturally orders the items by date but it could be an idea

**Comment by ThoDon** [comment]
I can see why @Androz2091 implemented the code this way, and as I'm not 100% sure that each match get effectively displayed, I think having a time based check is probably more efficient than checking every items and comparing theirs names or prices with each other.

Having a "lastItemTimestamp" as we do now allows to know directly if any item we get is rightfully newer than the last one that go stored in db.

But I've been running the bot since this morning on quite active categories and every time I actually checked the research page directly on vinted, every item got matched with the bot's notification. You got any research url we could try to investigate ?

**Comment by ClementG7** [comment]
For the state and the country of the product, only one solution with web scrapping and it works very well.

**Comment by YatoGaml** [comment]
Hi 
image
I got that error can you have an idea ?

**Comment by ThoDon** [comment]
Damnit, I updated the start script, but it was meant to be used locally, I don't know how it might work on other people computer.
Easiest fix would be to take start-bots.js content (from the og repo) and paste it in your file, then run it.

If it works, then my update is porbably linked to my own configuration, if it doesn't, then you might require some more tools (yarn might be missing ? idk)

**Comment by ThoDon** [comment]
For good measure, I'll throw in a new pull request with corrected files.

**Pull request closed without merging**
